global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus' # Scrapes Prometheus itself
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector' # Scrapes OpenTelemetry Collector
    static_configs:
      - targets: ['otel-collector:8889'] # For application metrics exported via OTel
      # - targets: ['otel-collector:8888'] # For OTel collector's own metrics

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000'] # Grafana exposes its own metrics

  # Add other services you want Prometheus to scrape directly
  # Example:
  # - job_name: 'my-app'
  #   static_configs:
  #     - targets: ['my-app-host:my-app-port']