apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686 # Jaeger Query Frontend
    jsonData:
      tracesToLogs: # Optional: Link traces to logs in Loki
        datasourceUid: 'Loki' # This needs to match the Loki datasource UID (Grafana will assign one, or you can set it)
        tags: ['job', 'instance', 'pod', 'namespace'] # Adjust tags as needed
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
    editable: true